name: CI
on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2018.4.15f1
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Activate Unity
      run: >
        echo "$UNITY_LICENSE" > /Unity_v2018.x.ulf

        /opt/Unity/Editor/Unity
        -batchmode -nographics -quit -logFile
        -manualLicenseFile /Unity_v2018.x.ulf || true

        rm /Unity_v2018.x.ulf

    - name: Run editor tests
      run: >
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24'
        /opt/Unity/Editor/Unity
        -batchmode -logFile
        -projectPath .
        -runTests -testPlatform editmode
        -testResults /Build/TestResults-EditMode.xml

        cat /Build/TestResults-EditMode.xml | grep test-run | grep result

    - name: Run runtime tests
      run: >
        xvfb-run --auto-servernum --server-args='-screen 0 640x480x24'
        /opt/Unity/Editor/Unity
        -batchmode -logFile
        -projectPath .
        -runTests -testPlatform playmode
        -testResults /Build/TestResults-PlayMode.xml

        cat /Build/TestResults-PlayMode.xml | grep test-run | grep result

    - name: Build unitypackage
      run: >
        mkdir -p /Build

        /opt/Unity/Editor/Unity
        -batchmode -nographics -quit -logFile
        -projectPath .
        -exportPackage
        Assets/Scripts/ColorHash.cs
        /Build/ColorHash.unitypackage

    - name: Upload unitypackage
      uses: actions/upload-artifact@v2
      with:
        name: ColorHash.unitypackage
        path: /Build/ColorHash.unitypackage
